---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp-k8s-01
  name: k8s-01-svc
  namespace: k8s-01
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wp-k8s-01
    tier: frontend
  sessionAffinity: None
  type: ClusterIP
