---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-disk
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: sql-test
  name: sql-test-pv-claim
  namespace: k8s-01
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
  volumeMode: Filesystem
  volumeName: pvc-1329b729-127e-4a9e-8842-fe5a820a0f20
