---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-disk
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: sql-test
  name: sql-test-pv-claim
  namespace: k8s-02
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
  volumeMode: Filesystem
  volumeName: pvc-e1bfc90f-0bdd-48af-a7ed-6f0a7c07bc9b
