---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: webhook
    helm.sh/chart: cert-manager-v0.12.0
  name: cert-manager-webhook
  namespace: cert-manager
secrets:
- name: cert-manager-webhook-token-gm4tl
