---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cainjector
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: cainjector
    helm.sh/chart: cert-manager-v0.12.0
  name: cert-manager-cainjector
  namespace: cert-manager
secrets:
- name: cert-manager-cainjector-token-wsjsv
