---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: webhook
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: webhook
    helm.sh/chart: cert-manager-v0.12.0
  name: cert-manager-webhook
  namespace: cert-manager
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webhook
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: webhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webhook
        app.kubernetes.io/instance: cert-manager
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/name: webhook
        helm.sh/chart: cert-manager-v0.12.0
    spec:
      containers:
      - args:
        - "--v=2"
        - "--secure-port=10250"
        - "--tls-cert-file=/certs/tls.crt"
        - "--tls-private-key-file=/certs/tls.key"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/jetstack/cert-manager-webhook:v0.12.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/livez"
            port: 6080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: cert-manager
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: "/healthz"
            port: 6080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        volumeMounts:
        - mountPath: "/certs"
          name: certs
      serviceAccount: cert-manager-webhook
      serviceAccountName: cert-manager-webhook
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: cert-manager-webhook-tls
