---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cert-manager
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: cert-manager
    helm.sh/chart: cert-manager-v0.12.0
  name: cert-manager
  namespace: cert-manager
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cert-manager
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: cert-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: '9402'
        prometheus.io/scrape: 'true'
      labels:
        app: cert-manager
        app.kubernetes.io/instance: cert-manager
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/name: cert-manager
        helm.sh/chart: cert-manager-v0.12.0
    spec:
      containers:
      - args:
        - "--v=2"
        - "--cluster-resource-namespace=$(POD_NAMESPACE)"
        - "--leader-election-namespace=kube-system"
        - "--webhook-namespace=$(POD_NAMESPACE)"
        - "--webhook-ca-secret=cert-manager-webhook-ca"
        - "--webhook-serving-secret=cert-manager-webhook-tls"
        - "--webhook-dns-names=cert-manager-webhook,cert-manager-webhook.cert-manager,cert-manager-webhook.cert-manager.svc"
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/jetstack/cert-manager-controller:v0.12.0
        imagePullPolicy: IfNotPresent
        name: cert-manager
        ports:
        - containerPort: 9402
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
      serviceAccount: cert-manager
      serviceAccountName: cert-manager
