---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-file
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: wp-k8s-03
  name: wp-test-pv-claim
  namespace: k8s-03
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: shared-standard
  volumeMode: Filesystem
  volumeName: pvc-4478125d-7ce8-476c-a028-d392d81310c7
